# Generated by Django 5.0.1 on 2024-02-29 03:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
    ]
