# Generated by Django 5.0.1 on 2024-02-29 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(max_length=100)),
                ('firstName', models.CharField(max_length=100)),
                ('lastName', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=150)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('fav_genre', models.CharField(max_length=100)),
                ('fav_movie', models.CharField(max_length=100)),
            ],
        ),
    ]
