# Generated by Django 5.0.1 on 2024-03-24 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.CharField(max_length=150)),
                ('quantity', models.IntegerField(max_length=1000)),
                ('cost', models.FloatField(max_length=1000000)),
            ],
        ),
    ]
