# Generated by Django 5.0.1 on 2024-03-24 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_orders'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='cost',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='orders',
            name='quantity',
            field=models.IntegerField(),
        ),
    ]
