# Generated by Django 5.0.1 on 2024-03-24 23:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_alter_orders_cost_alter_orders_quantity'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Orders',
        ),
    ]
